# Generated by Django 5.2.16 on 2026-08-01 05:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CUENTA_BANCARIA', 'Cuenta bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=25),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_cuotas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)]),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Cuenta bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('BILLETERA', 'Otra billetera digital'), ('AHORRO', 'Cuenta de ahorro'), ('OTRO', 'Otro')], max_length=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuenta'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='categoria',
            field=models.ForeignKey(limit_choices_to={'tipo': 'GASTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='finanzas.categoria'),
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Tarjeta CMR principal', max_length=100)),
                ('entidad', models.CharField(choices=[('OH', 'Financiera OH!'), ('CMR', 'CMR Falabella'), ('BCP', 'BCP'), ('INTERBANK', 'Interbank'), ('BBVA', 'BBVA'), ('SCOTIABANK', 'Scotiabank'), ('OTRA', 'Otra entidad')], max_length=20)),
                ('ultimos_digitos', models.CharField(blank=True, help_text='Solo los últimos cuatro dígitos.', max_length=4)),
                ('linea_credito', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_inicial_usado', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dia_cierre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('dia_pago', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_tarjeta', to='finanzas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_tarjetas', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.tarjetacredito')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('servicio', models.CharField(choices=[('LUZ', 'Luz'), ('AGUA', 'Agua'), ('INTERNET', 'Internet'), ('ALQUILER', 'Alquiler'), ('GAS', 'Gas'), ('TELEFONO', 'Teléfono'), ('SEGURO', 'Seguro'), ('OTRO', 'Otro')], max_length=20)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CUENTA_BANCARIA', 'Cuenta bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=25)),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frecuencia', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=15)),
                ('proxima_fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'GASTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='finanzas.categoria')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='finanzas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_recurrentes', to=settings.AUTH_USER_MODEL)),
                ('tarjeta_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='finanzas.tarjetacredito')),
            ],
            options={
                'ordering': ['proxima_fecha', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tarjeta_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.tarjetacredito'),
        ),
    ]
