# Generated by Django 5.2.16 on 2026-08-01 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_personas_titulares(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Persona = apps.get_model('finanzas', 'Persona')
    Movimiento = apps.get_model('finanzas', 'Movimiento')

    for usuario in User.objects.all():
        nombre = f"{usuario.first_name} {usuario.last_name}".strip() or usuario.username
        persona, _ = Persona.objects.get_or_create(
            usuario=usuario,
            nombre=nombre,
            defaults={'relacion': 'TITULAR'},
        )
        Movimiento.objects.filter(usuario=usuario, persona__isnull=True).update(
            persona=persona
        )


def mantener_personas(apps, schema_editor):
    # Los perfiles se conservan si se revierte la migración de datos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_movimiento_actualizado_movimiento_comprobante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('relacion', models.CharField(choices=[('TITULAR', 'Titular'), ('PAREJA', 'Pareja'), ('HIJO', 'Hijo/a'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], default='TITULAR', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#635bff', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_financieras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Persona a quien corresponde este ingreso o egreso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.persona'),
        ),
        migrations.RunPython(crear_personas_titulares, mantener_personas),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='persona_unica_por_usuario'),
        ),
    ]
