# Generated by Django 5.2.16 on 2026-08-02 03:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_remove_tarjetacredito_ultimos_digitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='cuenta_vinculada',
            field=models.ForeignKey(blank=True, help_text='Cuenta cuyo saldo se descuenta al usar una tarjeta de débito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_debito', to='finanzas.cuenta'),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], default='CREDITO', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='dia_cierre',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='dia_pago',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='linea_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
