/* Masterfull Finanzas · SPA para GitHub Pages + Supabase */
const NAV = [
  ['PRINCIPAL'],['resumen','dashboard','Resumen'],['personas','users','Personas'],['movimientos','transfer','Movimientos'],
  ['GESTIÓN'],['cuentas','wallet','Cuentas'],['propietarios','users','Propietarios'],['instituciones','wallet','Instituciones'],['tarjetas','card','Tarjetas'],['presupuestos','budget','Presupuestos'],['categorias','tag','Categorías'],
  ['PLANIFICACIÓN'],['metas','target','Metas de ahorro'],['deudas','debt','Deudas'],['recurrentes','repeat','Recurrentes'],['flujo','calendar','Flujo mensual'],['reportes','chart','Reportes']
];
const META = {
  personas:{title:'Personas',eye:'PERFILES DEL HOGAR',singular:'persona'}, movimientos:{title:'Movimientos',eye:'INGRESOS Y EGRESOS',singular:'movimiento'},
  cuentas:{title:'Cuentas',eye:'TU DINERO DISPONIBLE',singular:'cuenta'}, propietarios:{title:'Propietarios',eye:'PERSONAS Y FONDOS COMPARTIDOS',singular:'propietario'}, instituciones:{title:'Instituciones financieras',eye:'BANCOS Y ENTIDADES',singular:'institución'}, tarjetas:{title:'Tarjetas',eye:'CRÉDITO Y PAGOS',singular:'tarjeta'},
  presupuestos:{title:'Presupuestos',eye:'CONTROL MENSUAL',singular:'presupuesto'}, categorias:{title:'Categorías',eye:'ORGANIZACIÓN',singular:'categoría'},
  metas:{title:'Metas de ahorro',eye:'PLANIFICACIÓN',singular:'meta'}, deudas:{title:'Deudas',eye:'COMPROMISOS',singular:'deuda'},
  recurrentes:{title:'Gastos recurrentes',eye:'PAGOS PROGRAMADOS',singular:'gasto recurrente'}, flujo:{title:'Flujo mensual',eye:'EVOLUCIÓN DEL MES'}, reportes:{title:'Reportes',eye:'ANÁLISIS FINANCIERO'}
};
const SCHEMAS = {
  personas:[['nombre','Nombre completo','text'],['relacion','Relación','select',['TITULAR','PAREJA','HIJO/A','FAMILIAR','OTRO']],['email','Correo','email'],['telefono','Teléfono','text'],['color','Color','color']],
  propietarios:[['nombre','Nombre','text'],['tipo','Tipo','select',['PERSONA','EMPRESA','COMPARTIDA']],['color','Color','color'],['icono','Icono','select',['PERSONA','FAMILIA','EMPRESA','HOGAR']],['estado','Estado','select',['ACTIVO','INACTIVO']]],
  instituciones:[['nombre','Nombre','text'],['tipo','Tipo de institución','select',['BANCO','CAJA','FINANCIERA','BILLETERA_DIGITAL','COOPERATIVA','OTRA']],['pais','País','select',['PE','OTRO']],['color','Color','color'],['estado','Estado','select',['ACTIVO','INACTIVO']]],
  cuentas:[['propietario_id','Propietario de la cuenta','relation','propietarios'],['nombre','Nombre o alias de la cuenta','text'],['tipo','Tipo de cuenta','select',['EFECTIVO','BANCO','YAPE','PLIN','TARJETA_DE_DEBITO','TARJETA_DE_CREDITO','AHORRO','BILLETERA_DIGITAL','INVERSION','PRESTAMO','CREDITO','CAJA','OTRO']],['institucion_id','Institución financiera','relation','instituciones'],['saldo_inicial','Saldo inicial','number'],['moneda','Moneda','select',['PEN','USD','EUR','GBP','JPY','CLP','COP','MXN','BRL']],['fecha_saldo_inicial','Fecha del saldo inicial','date'],['color','Color','color'],['icono','Icono','select',['EFECTIVO','BANCO','BILLETERA','TARJETA','AHORRO','INVERSION','CAJA']],['descripcion','Descripción','textarea'],['estado','Estado','select',['ACTIVA','INACTIVA','ARCHIVADA']]],
  categorias:[['nombre','Nombre','text'],['tipo','Tipo','select',['INGRESO','GASTO']],['color','Color','color']],
  tarjetas:[['tipo','Tipo de tarjeta','select',['CREDITO','DEBITO']],['nombre','Nombre de la tarjeta','text'],['entidad','Entidad emisora','select',['OH','CMR','BCP','INTERBANK','BBVA','SCOTIABANK','OTRA']],['cuenta_id','Cuenta bancaria vinculada','relation','cuentas'],['linea_credito','Línea de crédito','number'],['saldo_inicial_usado','Deuda inicial utilizada','number'],['dia_cierre','Día de cierre','number'],['dia_pago','Día límite de pago','number']],
  movimientos:[['tipo','Tipo','select',['INGRESO','GASTO']],['monto','Monto','number'],['fecha','Fecha','date'],['categoria_id','Categoría','relation','categorias'],['persona_id','Persona','relation','personas'],['medio_pago','Forma de pago','select',['EFECTIVO','CUENTA_BANCARIA','YAPE','PLIN','TARJETA_DEBITO','TARJETA_CREDITO','OTRO']],['cuenta_id','Cuenta de origen o destino','relation','cuentas'],['tarjeta_id','Tarjeta utilizada','relation','tarjetas'],['numero_cuotas','Número de cuotas','number'],['descripcion','Descripción','text'],['notas','Notas','textarea']],
  presupuestos:[['categoria_id','Categoría de gasto','relation','categorias'],['mes','Mes','month'],['limite','Límite','number']],
  metas:[['nombre','Nombre de la meta','text'],['monto_objetivo','Monto objetivo','number'],['monto_actual','Monto ahorrado','number'],['fecha_objetivo','Fecha objetivo','date']],
  deudas:[['acreedor','Acreedor','text'],['descripcion','Descripción','text'],['monto_total','Monto total','number'],['monto_pagado','Monto pagado','number'],['fecha_vencimiento','Vencimiento','date'],['estado','Estado','select',['PENDIENTE','PAGADA']]],
  recurrentes:[['nombre','Nombre','text'],['servicio','Servicio','select',['LUZ','AGUA','INTERNET','ALQUILER','GAS','TELÉFONO','SEGURO','OTRO']],['categoria_id','Categoría','relation','categorias'],['monto_estimado','Monto estimado','number'],['frecuencia','Frecuencia','select',['MENSUAL','QUINCENAL','SEMANAL','ANUAL']],['proxima_fecha','Próxima fecha','date']]
};
const DEMO = {
  personas:[{id:'p1',nombre:'Titular',relacion:'TITULAR',color:'#315efb'}],
  propietarios:[{id:'o1',nombre:'Titular',tipo:'PERSONA',color:'#315efb',icono:'PERSONA',estado:'ACTIVO'},{id:'o2',nombre:'Compartida',tipo:'COMPARTIDA',color:'#14b8a6',icono:'FAMILIA',estado:'ACTIVO'}],
  instituciones:[{id:'i1',nombre:'BCP',tipo:'BANCO',pais:'PE',color:'#0055a5',estado:'ACTIVO'},{id:'i2',nombre:'Yape',tipo:'BILLETERA_DIGITAL',pais:'PE',color:'#742284',estado:'ACTIVO'}],
  cuentas:[{id:'c1',propietario_id:'o1',nombre:'Billetera',tipo:'EFECTIVO',institucion_id:null,saldo_inicial:1200,moneda:'PEN',fecha_saldo_inicial:todayISO(),color:'#315efb',icono:'EFECTIVO',estado:'ACTIVA'},{id:'c2',propietario_id:'o1',nombre:'Yape principal',tipo:'YAPE',institucion_id:'i2',saldo_inicial:350,moneda:'PEN',fecha_saldo_inicial:todayISO(),color:'#742284',icono:'BILLETERA',estado:'ACTIVA'}],
  categorias:[{id:'ca1',nombre:'Sueldo',tipo:'INGRESO',color:'#17865d'},{id:'ca2',nombre:'Alimentación',tipo:'GASTO',color:'#e27058'},{id:'ca3',nombre:'Servicios',tipo:'GASTO',color:'#8269d8'}],
  tarjetas:[{id:'t1',tipo:'CREDITO',nombre:'CMR principal',entidad:'CMR',cuenta_id:null,linea_credito:3000,saldo_inicial_usado:420,dia_cierre:15,dia_pago:5}],
  movimientos:[{id:'m1',tipo:'INGRESO',monto:2200,fecha:todayISO(),categoria_id:'ca1',cuenta_id:'c1',persona_id:'p1',medio_pago:'CUENTA_BANCARIA',descripcion:'Ingreso mensual'},{id:'m2',tipo:'GASTO',monto:185,fecha:todayISO(),categoria_id:'ca2',cuenta_id:'c1',persona_id:'p1',medio_pago:'EFECTIVO',descripcion:'Compra semanal'}],
  presupuestos:[{id:'pr1',categoria_id:'ca2',mes:todayISO().slice(0,7),limite:700}], metas:[{id:'me1',nombre:'Fondo de emergencia',monto_objetivo:5000,monto_actual:1200,fecha_objetivo:''}],
  deudas:[{id:'d1',acreedor:'Compra personal',descripcion:'',monto_total:900,monto_pagado:300,estado:'PENDIENTE'}], recurrentes:[{id:'r1',nombre:'Internet hogar',servicio:'INTERNET',categoria_id:'ca3',monto_estimado:89.9,frecuencia:'MENSUAL',proxima_fecha:todayISO()}]
};
const ACCOUNT_NATURE={EFECTIVO:'ACTIVO',BANCO:'ACTIVO',YAPE:'ACTIVO',PLIN:'ACTIVO',TARJETA_DE_DEBITO:'ACTIVO',AHORRO:'ACTIVO',BILLETERA_DIGITAL:'ACTIVO',INVERSION:'ACTIVO',CAJA:'ACTIVO',OTRO:'ACTIVO',TARJETA_DE_CREDITO:'PASIVO',PRESTAMO:'PASIVO',CREDITO:'PASIVO'};
const ACCOUNT_SUGGESTIONS={EFECTIVO:['Billetera','Caja principal','Caja chica','Efectivo personal','Caja del hogar','Dinero en casa'],BANCO:['Cuenta de ahorros','Cuenta sueldo','Cuenta corriente','Cuenta negocio'],YAPE:['Yape principal','Yape personal','Yape negocio'],PLIN:['Plin principal','Plin personal','Plin negocio'],TARJETA_DE_CREDITO:['CMR Falabella','Tarjeta Oh!','Ripley','Visa','Mastercard','Diners Club','American Express'],AHORRO:['Fondo de emergencia','Ahorro para vivienda','Ahorro para matrimonio','Ahorro para vacaciones','Ahorro para estudios','Ahorro para vehículo','Ahorro para negocio','Ahorro para jubilación'],INVERSION:['Fondo de inversión','Acciones','Criptomonedas','Depósito a plazo','AFP','Fondo mutuo']};
const MONEY_FIELDS=new Set(['saldo_inicial','linea_credito','saldo_inicial_usado','monto','limite','monto_objetivo','monto_actual','monto_total','monto_pagado','monto_estimado']);
const state={page:'resumen',user:null,data:{},demo:false,editing:null,accountFilters:{}}; let sb=null, authMode='login';
const $=s=>document.querySelector(s), money=n=>`S/ ${Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function currencyMoney(value,currency='PEN'){const symbols={PEN:'S/',USD:'US$',EUR:'€',GBP:'£',JPY:'¥',CLP:'CLP$',COP:'COL$',MXN:'MX$',BRL:'R$'};return `${symbols[currency]||currency} ${Number(value||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function todayISO(){return new Date().toISOString().slice(0,10)} function monthISO(){return todayISO().slice(0,7)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function configured(){const c=window.MASTERFULL_CONFIG||{};return /^https:\/\/.+\.supabase\.co$/.test(c.supabaseUrl||'')&&!!c.supabaseAnonKey}
function navHTML(){return NAV.map(x=>x.length===1?`<small>${x[0]}</small>`:`<a href="#${x[0]}" data-page="${x[0]}"><span class="nav-icon"><svg aria-hidden="true" focusable="false"><use href="#i-${x[1]}"></use></svg></span>${x[2]}</a>`).join('')}
async function boot(){ $('#navigation').innerHTML=navHTML(); $('#today').textContent=new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()); bind();
  if(!configured()){state.demo=true;state.user={id:'demo',email:'modo@demostracion.pe',user_metadata:{full_name:'Modo demostración'}};loadDemo();showApp();return}
  sb=window.supabase.createClient(window.MASTERFULL_CONFIG.supabaseUrl,window.MASTERFULL_CONFIG.supabaseAnonKey);const {data}=await sb.auth.getSession();if(data.session){state.user=data.session.user;await loadAll();showApp()}else showAuth();sb.auth.onAuthStateChange(async(_,session)=>{if(session){state.user=session.user;await loadAll();showApp()}else showAuth()})}
function bind(){window.addEventListener('hashchange',route);$('#add-main').onclick=()=>openForm(defaultEntity());$('#logout').onclick=async()=>state.demo?toast('El modo demostración no necesita cerrar sesión'):sb.auth.signOut();$('#auth-toggle').onclick=toggleAuth;$('#auth-form').onsubmit=submitAuth;$('#record-form').addEventListener('submit',saveForm);$('#quick-owner-form')?.addEventListener('submit',saveQuickOwner);$('#content').addEventListener('click',contentClick)}
function showAuth(){$('#auth').classList.remove('hidden');$('#app').classList.add('hidden')} function showApp(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');const name=state.user?.user_metadata?.full_name||state.user?.email?.split('@')[0]||'Mi cuenta';$('#profile-name').textContent=name;$('#avatar').textContent=name[0].toUpperCase();$('#profile-mode').textContent=state.demo?'Modo demostración':'Datos protegidos';route()}
function toggleAuth(){authMode=authMode==='login'?'signup':'login';$('#auth-title').textContent=authMode==='login'?'Bienvenido de nuevo':'Crea tu cuenta';$('#auth-copy').textContent=authMode==='login'?'Ingresa para continuar organizando tus finanzas.':'Tus registros estarán separados y protegidos.';$('#auth-form button').textContent=authMode==='login'?'Iniciar sesión':'Crear mi cuenta';$('#auth-toggle').textContent=authMode==='login'?'¿No tienes cuenta? Crear cuenta':'¿Ya tienes cuenta? Iniciar sesión'}
async function submitAuth(e){e.preventDefault();const email=$('#auth-email').value.trim(),password=$('#auth-password').value;const res=authMode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(res.error)toast(res.error.message);else toast(authMode==='login'?'Sesión iniciada':'Cuenta creada. Revisa tu correo si se solicita confirmación.')}
function normalizeData(){(state.data.propietarios||[]).forEach(x=>{x.tipo=x.tipo||'PERSONA';x.estado=x.estado||'ACTIVO'});(state.data.instituciones||[]).forEach(x=>x.estado=x.estado||'ACTIVO');(state.data.cuentas||[]).forEach(x=>{x.estado=x.estado||'ACTIVA';x.fecha_saldo_inicial=x.fecha_saldo_inicial||todayISO();x.moneda=x.moneda||'PEN'});(state.data.tarjetas||[]).forEach(x=>x.tipo=x.tipo||'CREDITO');(state.data.movimientos||[]).forEach(x=>x.numero_cuotas=Number(x.numero_cuotas||1))}
function loadDemo(){Object.entries(DEMO).forEach(([k,v])=>state.data[k]=JSON.parse(localStorage.getItem(`mf_${k}`)||JSON.stringify(v)));normalizeData()}
async function ensureSharedOwner(){if((state.data.propietarios||[]).some(x=>x.tipo==='COMPARTIDA'))return;const shared={nombre:'Compartida',tipo:'COMPARTIDA',color:'#14b8a6',icono:'FAMILIA',estado:'ACTIVO',user_id:state.user.id};const {data,error}=await sb.from('propietarios').insert(shared).select().single();if(!error)state.data.propietarios.unshift(data);else{const {data:owners}=await sb.from('propietarios').select('*').eq('tipo','COMPARTIDA');if(owners)state.data.propietarios=owners.concat(state.data.propietarios.filter(x=>x.tipo!=='COMPARTIDA'))}}
async function loadAll(){for(const table of Object.keys(SCHEMAS)){const {data,error}=await sb.from(table).select('*').order('created_at',{ascending:false});state.data[table]=error?[]:data}normalizeData();await ensureSharedOwner()}
function route(){state.page=(location.hash||'#resumen').slice(1);if(![...Object.keys(META),'resumen'].includes(state.page))state.page='resumen';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===state.page));const m=META[state.page]||{title:'Tu dinero, en contexto',eye:`RESUMEN DE ${new Intl.DateTimeFormat('es-PE',{month:'long'}).format(new Date()).toUpperCase()}`};$('#page-title').textContent=m.title;$('#page-eyebrow').textContent=m.eye;$('#add-main').classList.toggle('hidden',!SCHEMAS[state.page]);render()}
function sum(type){return (state.data.movimientos||[]).filter(x=>x.tipo===type&&String(x.fecha).startsWith(monthISO())).reduce((a,x)=>a+Number(x.monto),0)}
function accountBalance(c){const ms=(state.data.movimientos||[]).filter(x=>x.cuenta_id===c.id);return Number(c.saldo_inicial||0)+ms.reduce((a,x)=>a+(x.tipo==='INGRESO'?1:-1)*Number(x.monto),0)}
function debtTotal(){return (state.data.deudas||[]).reduce((a,x)=>a+Math.max(0,Number(x.monto_total)-Number(x.monto_pagado)),0)}
function cat(id){return (state.data.categorias||[]).find(x=>x.id===id)||{nombre:'Sin categoría',color:'#94a3b8'}}
function account(id){return (state.data.cuentas||[]).find(x=>x.id===id)||null}
function card(id){return (state.data.tarjetas||[]).find(x=>x.id===id)||null}
function owner(id){return (state.data.propietarios||[]).find(x=>x.id===id)||null}
function institution(id){return (state.data.instituciones||[]).find(x=>x.id===id)||null}
function accountNature(item){return ACCOUNT_NATURE[item?.tipo]||'ACTIVO'}
function cardUsed(item){return Number(item?.saldo_inicial_usado||0)+(state.data.movimientos||[]).filter(x=>x.tipo==='GASTO'&&x.medio_pago==='TARJETA_CREDITO'&&x.tarjeta_id===item?.id).reduce((total,x)=>total+Number(x.monto||0),0)}
function render(){if(state.page==='resumen')renderDashboard();else if(state.page==='cuentas')renderAccounts();else if(state.page==='flujo'||state.page==='reportes')renderReports();else renderEntity(state.page)}
function filterOptions(items,value,label,display=x=>x.nombre){return `<option value="">${label}</option>${items.map(x=>`<option value="${x.id||x}" ${(x.id||x)===value?'selected':''}>${esc(display(x))}</option>`).join('')}`}
function renderAccounts(){
 const f=state.accountFilters,all=state.data.cuentas||[],owners=(state.data.propietarios||[]).filter(x=>x.estado!=='INACTIVO'),institutions=(state.data.instituciones||[]).filter(x=>x.estado!=='INACTIVO');
 const visible=all.filter(x=>{const o=owner(x.propietario_id),i=institution(x.institucion_id),text=`${x.nombre} ${o?.nombre||''} ${i?.nombre||''}`.toLowerCase();return(!f.search||text.includes(f.search.toLowerCase()))&&(!f.owner||x.propietario_id===f.owner)&&(!f.type||x.tipo===f.type)&&(!f.institution||x.institucion_id===f.institution)&&(!f.currency||x.moneda===f.currency)&&(!f.status?x.estado!=='ARCHIVADA':x.estado===f.status)&&(!f.scope||(f.scope==='COMPARTIDA'?o?.tipo==='COMPARTIDA':o?.tipo!=='COMPARTIDA'))});
 const totals={};all.filter(x=>x.estado==='ACTIVA').forEach(x=>{const currency=x.moneda||'PEN',value=Math.abs(accountBalance(x));totals[currency]??={assets:0,liabilities:0};accountNature(x)==='PASIVO'?totals[currency].liabilities+=value:totals[currency].assets+=value});
 const totalLines=(key,net=false)=>Object.entries(totals).map(([currency,v])=>`<small>${currency}</small><strong>${currencyMoney(net?v.assets-v.liabilities:v[key],currency)}</strong>`).join('')||'<strong>Sin saldos</strong>';
 const types=Object.keys(ACCOUNT_NATURE),currencies=['PEN','USD','EUR','GBP','JPY','CLP','COP','MXN','BRL'];
 $('#content').innerHTML=`<section class="account-summary"><article><span>Activos</span>${totalLines('assets')}</article><article><span>Deudas</span>${totalLines('liabilities')}</article><article><span>Patrimonio neto</span>${totalLines('',true)}</article><article><span>Cuentas activas</span><strong>${all.filter(x=>x.estado==='ACTIVA').length}</strong></article></section><section class="account-filters panel"><input name="search" value="${esc(f.search||'')}" placeholder="Buscar por cuenta, institución o propietario"><select name="owner">${filterOptions(owners,f.owner,'Todos los propietarios')}</select><select name="type">${filterOptions(types,f.type,'Todos los tipos',x=>optionLabel(x))}</select><select name="institution">${filterOptions(institutions,f.institution,'Todas las instituciones')}</select><select name="currency">${filterOptions(currencies,f.currency,'Todas las monedas',x=>optionLabel(x))}</select><select name="status">${filterOptions(['ACTIVA','INACTIVA','ARCHIVADA'],f.status,'Activas y no archivadas',x=>optionLabel(x))}</select><select name="scope"><option value="">Personales y compartidas</option><option value="PERSONAL" ${f.scope==='PERSONAL'?'selected':''}>Personales</option><option value="COMPARTIDA" ${f.scope==='COMPARTIDA'?'selected':''}>Compartidas</option></select><button type="button" class="btn primary" data-account-filter>Aplicar filtros</button><button type="button" class="btn secondary" data-account-clear>Limpiar</button></section><div class="section-head"><div><h2>${visible.length} cuenta${visible.length===1?'':'s'}</h2><p class="caption">Activos y pasivos separados por moneda, propietario e institución.</p></div></div><section class="account-list">${visible.length?visible.map(x=>{const o=owner(x.propietario_id),i=institution(x.institucion_id),nature=accountNature(x);return `<article class="account-card"><div class="account-icon" style="--account-color:${esc(x.color||'#315efb')}">${esc((x.icono||'CAJA').slice(0,1))}</div><div class="account-main"><strong>${esc(x.nombre)}</strong><small>${esc(o?.nombre||'Propietario pendiente')} · ${esc(optionLabel(x.tipo))}${i?` · ${esc(i.nombre)}`:''}</small><span class="badge ${nature.toLowerCase()}">${nature==='ACTIVO'?'Activo':'Pasivo'}</span></div><div class="account-balance"><strong>${currencyMoney(Math.abs(accountBalance(x)),x.moneda)}</strong><small>${esc(x.moneda)} · ${esc(optionLabel(x.estado||'ACTIVA'))}</small></div><div class="account-actions"><button data-account-movements="${x.id}">Ver movimientos</button><button data-edit="cuentas" data-id="${x.id}">Editar</button><button data-archive="${x.id}">${x.estado==='ARCHIVADA'?'Reactivar':'Archivar'}</button></div></article>`}).join(''):'<div class="empty panel">No hay cuentas para estos filtros.</div>'}</section>`;
}
function renderDashboard(){const income=sum('INGRESO'),expense=sum('GASTO'),balance=income-expense,accounts=(state.data.cuentas||[]).reduce((a,x)=>a+accountBalance(x),0),rate=income?Math.round(balance/income*100):0;const mov=[...(state.data.movimientos||[])].sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha))).slice(0,6);const cats={};(state.data.movimientos||[]).filter(x=>x.tipo==='GASTO'&&String(x.fecha).startsWith(monthISO())).forEach(x=>cats[x.categoria_id]=(cats[x.categoria_id]||0)+Number(x.monto));
 $('#content').innerHTML=`<section class="summary-grid"><article class="hero-card"><div class="hero-head"><div><span class="overline">Posición actual</span><h2>Disponible en tus cuentas</h2></div><span class="date-chip">Actualizado hoy</span></div><div class="main-balance"><small>S/</small>${Number(accounts).toLocaleString('es-PE',{minimumFractionDigits:2})}</div><p class="caption">Saldo combinado de ${(state.data.cuentas||[]).length} cuentas activas.</p><div class="cashflow"><div><span>INGRESOS DEL MES</span><strong class="positive">+ ${money(income)}</strong></div><div><span>EGRESOS DEL MES</span><strong class="negative">− ${money(expense)}</strong></div><div><span>BALANCE MENSUAL</span><strong class="${balance>=0?'positive':'negative'}">${money(balance)}</strong></div></div></article><aside class="insight-card"><p class="eyebrow">LECTURA DEL MES</p><h2>${income?`Conservaste el ${rate}% de tus ingresos.`:'Empieza registrando el movimiento de hoy.'}</h2><p>${balance>=0?'Tu balance es positivo; mantén el registro al día.':'Tus egresos superaron lo ingresado durante este periodo.'}</p><div class="quick-actions"><button class="btn" data-new="movimientos" data-type="INGRESO">↓ Ingreso</button><button class="btn" data-new="movimientos" data-type="GASTO">↑ Egreso</button></div></aside></section><section class="stats"><article class="stat-card"><span>PATRIMONIO ESTIMADO</span><strong>${money(accounts-debtTotal())}</strong></article><article class="stat-card"><span>DEUDAS PENDIENTES</span><strong class="negative">${money(debtTotal())}</strong></article><article class="stat-card"><span>METAS ACTIVAS</span><strong>${(state.data.metas||[]).length}</strong></article></section><section class="two-column"><article class="panel"><div class="panel-head"><div><span class="overline">TU HISTORIA RECIENTE</span><h2>Movimientos</h2></div><a class="link-button" href="#movimientos">Abrir historial →</a></div>${mov.length?mov.map(x=>`<div class="transaction"><span class="transaction-icon ${x.tipo==='INGRESO'?'income':''}">${x.tipo==='INGRESO'?'↓':'↑'}</span><span class="transaction-info"><strong>${esc(x.descripcion||cat(x.categoria_id).nombre)}</strong><small>${esc(x.fecha)} · ${esc(cat(x.categoria_id).nombre)}</small></span><strong class="amount ${x.tipo==='INGRESO'?'positive':'negative'}">${x.tipo==='INGRESO'?'+':'−'} ${money(x.monto)}</strong></div>`).join(''):'<div class="empty">Aún no hay movimientos.</div>'}</article><article class="panel"><div class="panel-head"><div><span class="overline">EN QUÉ SE FUE</span><h2>Egresos por categoría</h2></div></div>${Object.entries(cats).length?Object.entries(cats).map(([id,v])=>`<div class="category-row"><div><span>${esc(cat(id).nombre)}</span><strong>${money(v)}</strong></div><div class="bar"><i style="width:${expense?v/expense*100:0}%;background:${cat(id).color}"></i></div></div>`).join(''):'<div class="empty">Sin egresos este mes.</div>'}</article></section>`}
function defaultEntity(){return SCHEMAS[state.page]?state.page:'movimientos'}
function renderEntity(entity){let rows=state.data[entity]||[];if(entity==='movimientos'&&state.movementAccountFilter)rows=rows.filter(x=>x.cuenta_id===state.movementAccountFilter);const cols={personas:['nombre','relacion','email'],propietarios:['nombre','tipo','estado'],instituciones:['nombre','tipo','pais','estado'],categorias:['nombre','tipo'],tarjetas:['nombre','tipo','entidad','origen_tarjeta'],movimientos:['fecha','categoria_id','medio_pago','origen_movimiento','tipo','monto'],presupuestos:['mes','categoria_id','limite'],metas:['nombre','monto_objetivo','monto_actual','fecha_objetivo'],deudas:['acreedor','monto_total','monto_pagado','estado'],recurrentes:['nombre','servicio','monto_estimado','proxima_fecha']}[entity];const labels={categoria_id:'Categoría',medio_pago:'Forma de pago',origen_tarjeta:'Cuenta o línea',origen_movimiento:'Cuenta o tarjeta',saldo_inicial:'Saldo inicial',linea_credito:'Línea',saldo_inicial_usado:'Utilizado',monto_objetivo:'Objetivo',monto_actual:'Ahorrado',monto_total:'Total',monto_pagado:'Pagado',proxima_fecha:'Próximo pago'};
 const filterNotice=entity==='movimientos'&&state.movementAccountFilter?`<div class="flow-guidance">Movimientos de ${esc(account(state.movementAccountFilter)?.nombre||'la cuenta seleccionada')} <button data-clear-movement-filter>Ver todos</button></div>`:'';
 $('#content').innerHTML=filterNotice+`<div class="section-head"><div><h2>${rows.length} registro${rows.length===1?'':'s'}</h2><p class="caption">Administra la información de ${META[entity].title.toLowerCase()}.</p></div></div><section class="panel table-panel"><div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${labels[c]||c.replaceAll('_',' ')}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td>${formatCell(c,r[c],r)}</td>`).join('')}<td class="actions">${entity==='instituciones'&&!r.user_id?'<span class="muted">Catálogo</span>':`<button data-edit="${entity}" data-id="${r.id}">Editar</button><button class="danger" data-delete="${entity}" data-id="${r.id}">Eliminar</button>`}</td></tr>`).join(''):`<tr><td class="empty" colspan="${cols.length+1}">No hay registros todavía. Usa “Nuevo registro” para comenzar.</td></tr>`}</tbody></table></div></section>`}
function formatCell(k,v,r){if(k==='categoria_id')return esc(cat(v).nombre);if(k==='medio_pago')return esc(String(v||'—').replaceAll('_',' '));if(k==='origen_tarjeta'){if(r.tipo==='DEBITO')return esc(account(r.cuenta_id)?.nombre||'Sin cuenta vinculada');const used=cardUsed(r);return `<strong>Línea ${money(r.linea_credito)}</strong><small class="table-note">Utilizado ${money(used)} · Disponible ${money(Math.max(0,Number(r.linea_credito||0)-used))}</small>`}if(k==='origen_movimiento'){const source=r.tarjeta_id?card(r.tarjeta_id):account(r.cuenta_id);return esc(source?.nombre||'—')}if(['monto','limite','saldo_inicial','linea_credito','saldo_inicial_usado','monto_objetivo','monto_actual','monto_total','monto_pagado','monto_estimado'].includes(k))return `<strong>${money(v)}</strong>`;if(k==='tipo')return `<span class="badge ${String(v).toLowerCase()}">${esc(optionLabel(String(v)))}</span>`;return esc(v||'—')}
function renderReports(){const byMonth={};(state.data.movimientos||[]).forEach(x=>{const m=String(x.fecha).slice(0,7);byMonth[m]??={income:0,expense:0};byMonth[m][x.tipo==='INGRESO'?'income':'expense']+=Number(x.monto)});const rows=Object.entries(byMonth).sort((a,b)=>b[0].localeCompare(a[0]));$('#content').innerHTML=`<section class="stats"><article class="stat-card"><span>INGRESOS ACUMULADOS</span><strong class="positive">${money((state.data.movimientos||[]).filter(x=>x.tipo==='INGRESO').reduce((a,x)=>a+Number(x.monto),0))}</strong></article><article class="stat-card"><span>EGRESOS ACUMULADOS</span><strong class="negative">${money((state.data.movimientos||[]).filter(x=>x.tipo==='GASTO').reduce((a,x)=>a+Number(x.monto),0))}</strong></article><article class="stat-card"><span>BALANCE DEL MES</span><strong>${money(sum('INGRESO')-sum('GASTO'))}</strong></article></section><section class="panel table-panel"><table><thead><tr><th>Periodo</th><th>Ingresos</th><th>Egresos</th><th>Balance</th></tr></thead><tbody>${rows.length?rows.map(([m,x])=>`<tr><td><strong>${m}</strong></td><td class="positive">${money(x.income)}</td><td class="negative">${money(x.expense)}</td><td><strong>${money(x.income-x.expense)}</strong></td></tr>`).join(''):'<tr><td colspan="4" class="empty">Registra movimientos para generar el análisis.</td></tr>'}</tbody></table></section>`}
function contentClick(e){const n=e.target.closest('[data-new]'),ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),filter=e.target.closest('[data-account-filter]'),clear=e.target.closest('[data-account-clear]'),archive=e.target.closest('[data-archive]'),movements=e.target.closest('[data-account-movements]'),clearMovements=e.target.closest('[data-clear-movement-filter]');if(n)openForm(n.dataset.new,null,{tipo:n.dataset.type});if(ed)openForm(ed.dataset.edit,(state.data[ed.dataset.edit]||[]).find(x=>x.id===ed.dataset.id));if(del)remove(del.dataset.delete,del.dataset.id);if(filter){const controls=$('.account-filters').querySelectorAll('input,select');state.accountFilters=Object.fromEntries(Array.from(controls).map(x=>[x.name,x.value.trim()]));renderAccounts()}if(clear){state.accountFilters={};renderAccounts()}if(archive)toggleAccountArchive(archive.dataset.archive);if(movements){state.movementAccountFilter=movements.dataset.accountMovements;location.hash='movimientos'}if(clearMovements){state.movementAccountFilter=null;renderEntity('movimientos')}}
function handleOwnerChoice(e){if(e.target.value!=='__new__')return;e.target.value='';const dialog=$('#quick-owner-dialog');$('#quick-owner-form').reset();dialog.showModal();dialog.querySelector('[name="nombre"]').focus()}
async function saveQuickOwner(e){e.preventDefault();if(e.submitter?.value==='cancel'){$('#quick-owner-dialog').close();return}const form=e.currentTarget,name=form.elements.nombre.value.trim().replace(/\s+/g,' '),type=form.elements.tipo.value,color=form.elements.color.value||'#315efb',icono=form.elements.icono.value||'PERSONA';if(!name){toast('El nombre del propietario es obligatorio.');return}if(name.length>80){toast('El nombre no puede superar 80 caracteres.');return}if((state.data.propietarios||[]).some(x=>x.nombre.trim().toLowerCase()===name.toLowerCase())){toast('Ya existe un propietario con ese nombre.');return}const obj={nombre:name,tipo:type,color,icono,estado:'ACTIVO'};if(state.demo){obj.id=crypto.randomUUID();state.data.propietarios.unshift(obj);localStorage.setItem('mf_propietarios',JSON.stringify(state.data.propietarios))}else{obj.user_id=state.user.id;const {data,error}=await sb.from('propietarios').insert(obj).select().single();if(error){toast(error.message);return}state.data.propietarios.unshift(data);obj.id=data.id}const select=$('#record-form [name="propietario_id"]');const option=document.createElement('option');option.value=obj.id;option.textContent=obj.nombre;select.insertBefore(option,select.querySelector('option[value="__new__"]'));select.value=obj.id;$('#quick-owner-dialog').close();toast('Propietario agregado')}
async function toggleAccountArchive(id){const item=account(id);if(!item)return;const estado=item.estado==='ARCHIVADA'?'ACTIVA':'ARCHIVADA';if(state.demo){item.estado=estado;localStorage.setItem('mf_cuentas',JSON.stringify(state.data.cuentas))}else{const {error}=await sb.from('cuentas').update({estado}).eq('id',id);if(error){toast(error.message);return}item.estado=estado}toast(estado==='ARCHIVADA'?'Cuenta archivada':'Cuenta reactivada');renderAccounts()}
function openForm(entity,row=null,preset={}){
  state.editing={entity,id:row?.id||null};
  const defaults=entity==='tarjetas'?{tipo:'CREDITO',saldo_inicial_usado:0}:entity==='movimientos'?{numero_cuotas:1}:entity==='cuentas'?{saldo_inicial:0,moneda:'PEN',fecha_saldo_inicial:todayISO(),color:'#315efb',icono:'CAJA',estado:'ACTIVA'}:entity==='propietarios'?{tipo:'PERSONA',color:'#315efb',icono:'PERSONA',estado:'ACTIVO'}:entity==='instituciones'?{tipo:'BANCO',pais:'PE',color:'#315efb',estado:'ACTIVO'}:{};
  const action=row?'Editar':entity==='movimientos'?'Nuevo':'Nueva';
  $('#dialog-title').textContent=`${action} ${META[entity].singular}`;
  $('#form-fields').innerHTML=`<div id="flow-guidance" class="flow-guidance wide"></div>`+SCHEMAS[entity].map(([name,label,type,opt])=>fieldHTML(name,label,type,opt,row?.[name]??preset[name]??defaults[name]??'')).join('')+(entity==='cuentas'?'<datalist id="account-name-suggestions"></datalist>':'');
  $('#record-form [name="medio_pago"]')?.addEventListener('change',updateFormFlow);
  $('#record-form [name="tipo"]')?.addEventListener('change',updateFormFlow);
  $('#record-form [name="propietario_id"]')?.addEventListener('change',handleOwnerChoice);
  updateFormFlow();
  $('#record-dialog').showModal();
}
function optionLabel(value){return ({PEN:'PEN - Sol peruano',USD:'USD - Dólar estadounidense',EUR:'EUR - Euro',GBP:'GBP - Libra esterlina',JPY:'JPY - Yen japonés',CLP:'CLP - Peso chileno',COP:'COP - Peso colombiano',MXN:'MXN - Peso mexicano',BRL:'BRL - Real brasileño',PERSONA:'Persona',EMPRESA:'Empresa',COMPARTIDA:'Compartida',ACTIVO:'Activo',PASIVO:'Pasivo',ACTIVA:'Activa',INACTIVA:'Inactiva',ARCHIVADA:'Archivada',INACTIVO:'Inactivo',EFECTIVO:'Efectivo',BANCO:'Banco',YAPE:'Yape',PLIN:'Plin',TARJETA_DE_DEBITO:'Tarjeta de débito',TARJETA_DE_CREDITO:'Tarjeta de crédito',AHORRO:'Ahorro',BILLETERA_DIGITAL:'Billetera digital',INVERSION:'Inversión',PRESTAMO:'Préstamo',CREDITO:'Crédito',CAJA:'Caja',OTRO:'Otro',DEBITO:'Débito',TARJETA_CREDITO:'Tarjeta de crédito',TARJETA_DEBITO:'Tarjeta de débito',CUENTA_BANCARIA:'Cuenta bancaria',COOPERATIVA:'Cooperativa',FINANCIERA:'Financiera',OTRA:'Otra'}[value]||String(value).toLowerCase().replaceAll('_',' '))}
function fieldHTML(name,label,type,opt,value){
  let control;
  const optional=(state.editing.entity==='movimientos'&&['persona_id','descripcion','notas'].includes(name))||(state.editing.entity==='tarjetas'&&['saldo_inicial_usado'].includes(name))||(state.editing.entity==='cuentas'&&['institucion_id','fecha_saldo_inicial','color','icono','descripcion'].includes(name));
  if(type==='month'&&String(value).length>7)value=String(value).slice(0,7);
  if(type==='select')control=`<select name="${name}" ${optional?'':'required'}><option value="">Selecciona</option>${opt.map(x=>`<option value="${x}" ${x==value?'selected':''}>${esc(optionLabel(x))}</option>`).join('')}</select>`;
  else if(type==='relation'){
    let list=state.data[opt]||[];
    if(opt==='cuentas')list=list.filter(x=>x.estado!=='ARCHIVADA');
    if(opt==='propietarios')list=list.filter(x=>x.estado!=='INACTIVO');
    if(opt==='instituciones')list=list.filter(x=>x.estado!=='INACTIVO');
    if(name==='categoria_id'&&state.editing.entity==='presupuestos')list=list.filter(x=>x.tipo==='GASTO');
    control=`<select name="${name}"><option value="">${name==='propietario_id'?'Seleccionar propietario':'Sin asignar'}</option>${list.map(x=>`<option value="${x.id}" ${x.id==value?'selected':''} ${name==='tarjeta_id'?`data-card-type="${x.tipo||'CREDITO'}"`:''}>${esc(x.nombre)}${name==='tarjeta_id'?` · ${esc(x.entidad)} (${esc(optionLabel(x.tipo||'CREDITO'))})`:''}</option>`).join('')}${name==='propietario_id'&&state.editing.entity==='cuentas'?'<option value="__new__">＋ Agregar nuevo propietario</option>':''}</select>`;
  }else if(type==='textarea')control=`<textarea name="${name}">${esc(value)}</textarea>`;
  else control=`<input name="${name}" type="${type}" value="${esc(value||(type==='date'?todayISO():''))}" ${type==='number'?'step="0.01" min="0" inputmode="decimal"':''} ${state.editing.entity==='cuentas'&&name==='nombre'?'list="account-name-suggestions" maxlength="100"':''} ${optional?'':'required'}>`;
  const help=state.editing.entity==='cuentas'&&name==='nombre'?'Escribe un nombre que te permita reconocerla fácilmente.':state.editing.entity==='cuentas'&&name==='saldo_inicial'?'Ingresa el saldo real de la cuenta en la fecha indicada.':'';
  return `<label data-field="${name}" class="${type==='textarea'?'wide':''}">${label}${optional?' <span class="optional-label">Opcional</span>':''}${control}${help?`<small class="field-help">${help}</small>`:''}</label>`;
}
function updateFormFlow(){
  const form=$('#record-form'),entity=state.editing?.entity;
  const setField=(name,visible,required=false)=>{const label=form.querySelector(`[data-field="${name}"]`);if(!label)return;label.hidden=!visible;const control=label.querySelector('input,select,textarea');control.disabled=!visible;control.required=visible&&required};
  const guidance=$('#flow-guidance');
  if(entity==='movimientos'){
    const payment=form.elements.medio_pago?.value,isCredit=payment==='TARJETA_CREDITO',isDebit=payment==='TARJETA_DEBITO',usesCard=isCredit||isDebit;
    setField('cuenta_id',!usesCard,!usesCard);setField('tarjeta_id',usesCard,usesCard);setField('numero_cuotas',isCredit,isCredit);
    const cardSelect=form.elements.tarjeta_id;
    if(cardSelect)Array.from(cardSelect.options).forEach(option=>{const type=option.dataset.cardType,allowed=!type||(isCredit&&type==='CREDITO')||(isDebit&&type==='DEBITO');option.hidden=!allowed;option.disabled=!allowed;if(option.selected&&!allowed)cardSelect.value=''});
    guidance.textContent=isCredit?'Compra a crédito: el monto aumentará la deuda de la tarjeta y no descontará ninguna cuenta hasta que registres su pago.':isDebit?'Compra con débito: el monto se descontará automáticamente de la cuenta vinculada a la tarjeta.':'Movimiento directo: selecciona la cuenta de donde sale el dinero o donde ingresa.';
  }else if(entity==='cuentas'){
    const type=form.elements.tipo?.value||'',requiresInstitution=['BANCO','YAPE','PLIN','TARJETA_DE_DEBITO','TARJETA_DE_CREDITO','BILLETERA_DIGITAL'].includes(type),nature=ACCOUNT_NATURE[type]||'ACTIVO';
    setField('propietario_id',true,true);setField('institucion_id',true,requiresInstitution);
    const suggestions=$('#account-name-suggestions');if(suggestions)suggestions.innerHTML=(ACCOUNT_SUGGESTIONS[type]||[]).map(x=>`<option value="${esc(x)}"></option>`).join('');
    guidance.textContent=type?`${optionLabel(type)} se registrará como ${nature==='PASIVO'?'pasivo (deuda)':'activo'}. ${requiresInstitution?'Selecciona la institución financiera.':'La institución es opcional para este tipo de cuenta.'}`:'Selecciona un propietario y el tipo de cuenta. Los nombres son alias; no necesitas repetir al propietario.';
  }else if(entity==='tarjetas'){
    const isDebit=form.elements.tipo?.value==='DEBITO';
    setField('cuenta_id',isDebit,isDebit);['linea_credito','dia_cierre','dia_pago'].forEach(name=>setField(name,!isDebit,!isDebit));setField('saldo_inicial_usado',!isDebit,false);
    guidance.textContent=isDebit?'Tarjeta de débito: vincúlala a la cuenta bancaria cuyo saldo se descontará en cada compra.':'Tarjeta de crédito: las compras aumentarán su deuda y el dinero saldrá de una cuenta recién cuando registres el pago.';
  }else guidance.hidden=true;
}
async function saveForm(e){
  e.preventDefault();
  if(e.submitter?.value==='cancel'){$('#record-dialog').close();return}
  const saveButton=$('#save-record'),previousLabel=saveButton.textContent;
  saveButton.disabled=true;saveButton.classList.add('is-loading');saveButton.setAttribute('aria-busy','true');saveButton.textContent='Guardando…';
  try{
    const {entity,id}=state.editing,obj=Object.fromEntries(new FormData($('#record-form')).entries());
    for(const [n,,t] of SCHEMAS[entity])if(t==='number'&&Object.hasOwn(obj,n)){const numeric=Number(obj[n]||0);obj[n]=MONEY_FIELDS.has(n)?numeric.toFixed(2):numeric}
    for(const [n,,t] of SCHEMAS[entity])if(t==='relation'&&obj[n]==='')obj[n]=null;
    if(['propietarios','instituciones','cuentas'].includes(entity)&&obj.nombre)obj.nombre=obj.nombre.trim().replace(/\s+/g,' ');
    if(entity==='propietarios'){
      if(!obj.nombre){toast('El nombre del propietario es obligatorio.');return}
      if(obj.nombre.length>80){toast('El nombre no puede superar 80 caracteres.');return}
      if((state.data.propietarios||[]).some(x=>x.id!==id&&x.nombre.trim().toLowerCase()===obj.nombre.toLowerCase())){toast('Ya existe un propietario con ese nombre.');return}
    }
    if(entity==='instituciones'&&(state.data.instituciones||[]).some(x=>x.id!==id&&x.nombre.trim().toLowerCase()===obj.nombre.toLowerCase())){toast('Ya existe una institución con ese nombre.');return}
    if(entity==='cuentas'){
      if(!obj.propietario_id||!obj.nombre||!obj.tipo||!obj.moneda||!Object.hasOwn(obj,'saldo_inicial')){toast('Completa propietario, nombre, tipo, saldo inicial y moneda.');return}
      if(obj.saldo_inicial<0){toast('Registra el saldo o la deuda inicial como un importe positivo.');return}
      if(['BANCO','YAPE','PLIN','TARJETA_DE_DEBITO','TARJETA_DE_CREDITO','BILLETERA_DIGITAL'].includes(obj.tipo)&&!obj.institucion_id){toast('Selecciona la institución financiera para este tipo de cuenta.');return}
      const duplicate=(state.data.cuentas||[]).some(x=>x.id!==id&&x.propietario_id===obj.propietario_id&&(x.nombre||'').trim().toLowerCase()===obj.nombre.toLowerCase()&&(x.institucion_id||null)===(obj.institucion_id||null)&&(x.moneda||'PEN')===obj.moneda);
      if(duplicate){toast('Ya existe una cuenta con el mismo propietario, alias, institución y moneda.');return}
      obj.naturaleza=ACCOUNT_NATURE[obj.tipo]||'ACTIVO';obj.estado=obj.estado||'ACTIVA';obj.fecha_saldo_inicial=obj.fecha_saldo_inicial||todayISO();
    }
    if(entity==='tarjetas'){
      if(obj.tipo==='DEBITO'){
        if(!obj.cuenta_id){toast('Selecciona la cuenta bancaria vinculada a la tarjeta de débito.');return}
        obj.linea_credito=null;obj.saldo_inicial_usado=0;obj.dia_cierre=null;obj.dia_pago=null;
      }else{
        obj.tipo='CREDITO';obj.cuenta_id=null;
        if(Number(obj.linea_credito)<=0||!obj.dia_cierre||!obj.dia_pago){toast('Completa la línea de crédito, el cierre y el día de pago.');return}
      }
    }
    if(entity==='movimientos'){
      const usesCredit=obj.medio_pago==='TARJETA_CREDITO',usesDebit=obj.medio_pago==='TARJETA_DEBITO',usesCard=usesCredit||usesDebit;
      if(usesCard&&obj.tipo!=='GASTO'){toast('Las tarjetas solo pueden utilizarse para registrar gastos.');return}
      if(usesCard){
        const selectedCard=card(obj.tarjeta_id),expected=usesCredit?'CREDITO':'DEBITO';
        if(!selectedCard){toast('Selecciona la tarjeta utilizada.');return}
        if((selectedCard.tipo||'CREDITO')!==expected){toast(`Selecciona una tarjeta de ${expected.toLowerCase()}.`);return}
        if(usesDebit){if(!selectedCard.cuenta_id){toast('Esta tarjeta de débito no tiene una cuenta vinculada.');return}obj.cuenta_id=selectedCard.cuenta_id;obj.numero_cuotas=1}
        else obj.cuenta_id=null;
      }else{
        if(!obj.cuenta_id){toast('Selecciona la cuenta de origen o destino.');return}
        obj.tarjeta_id=null;obj.numero_cuotas=1;
      }
    }
    if(entity==='presupuestos'&&obj.mes)obj.mes+=obj.mes.length===7?'-01':'';
    if(state.demo){
      obj.id=id||crypto.randomUUID();const list=state.data[entity];const i=list.findIndex(x=>x.id===id);i>=0?list.splice(i,1,obj):list.unshift(obj);localStorage.setItem(`mf_${entity}`,JSON.stringify(list));
    }else{
      obj.user_id=state.user.id;
      const query=id?sb.from(entity).update(obj).eq('id',id):sb.from(entity).insert(obj);
      const {data:saved,error}=await query.select().single();
      if(error){toast(error.code==='PGRST204'?'La base de datos necesita aplicar la actualización de tarjetas.':error.message);return}
      const list=state.data[entity]||[],i=list.findIndex(x=>x.id===id);
      i>=0?list.splice(i,1,saved):list.unshift(saved);state.data[entity]=list;
    }
    $('#record-dialog').close();toast('Registro guardado');render();
  }finally{
    saveButton.disabled=false;saveButton.classList.remove('is-loading');saveButton.removeAttribute('aria-busy');saveButton.textContent=previousLabel;
  }
}
async function remove(entity,id){if(entity==='cuentas'&&(state.data.movimientos||[]).some(x=>x.cuenta_id===id)){toast('Esta cuenta tiene movimientos. Archívala para conservar su historial.');return}if(entity==='propietarios'&&(state.data.cuentas||[]).some(x=>x.propietario_id===id)){toast('Este propietario tiene cuentas asociadas. Cámbialo a Inactivo.');return}if(!confirm('¿Eliminar este registro?'))return;if(state.demo){state.data[entity]=state.data[entity].filter(x=>x.id!==id);localStorage.setItem(`mf_${entity}`,JSON.stringify(state.data[entity]))}else{const {error}=await sb.from(entity).delete().eq('id',id);if(error){toast(error.message);return}await loadAll()}toast('Registro eliminado');render()}
boot().catch(e=>{console.error(e);toast('No se pudo iniciar la aplicación.')});
