services:
  - type: web
    name: masterfull-finanzas
    runtime: python
    branch: main
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /cuentas-usuario/login/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
